import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class InvoicePdfService {
  static Future<Uint8List> generateInvoicePdf({
    required String invoiceNumber,
    required String clientName,
    required String issueDate,
    required String dueDate,
    required String status,
    required double subtotal,
    required double vat,
    required double total,
    required List<Map<String, dynamic>> items,
    required String currencySymbol,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(
          40,
          40,
          40,
          40,
        ),
        header: (context) {
          return pw.Column(
            children: [
              pw.Row(
                mainAxisAlignment:
                pw.MainAxisAlignment.spaceBetween,
                crossAxisAlignment:
                pw.CrossAxisAlignment.start,
                children: [
                  pw.Column(
                    crossAxisAlignment:
                    pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'INVOICEPILOT',
                        style: pw.TextStyle(
                          fontSize: 20,
                          fontWeight: pw.FontWeight.bold,
                          color: PdfColors.blue,
                        ),
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(
                        'Professional Invoice',
                        style: pw.TextStyle(
                          fontSize: 9,
                          color: PdfColors.grey600,
                        ),
                      ),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment:
                    pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text(
                        'INVOICE',
                        style: pw.TextStyle(
                          fontSize: 28,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(
                        invoiceNumber,
                        style: pw.TextStyle(
                          fontSize: 14,
                          color: PdfColors.grey700,
                        ),
                      ),
                    ],
                  ),
                ],
              ),
              pw.SizedBox(height: 15),
              pw.Divider(
                color: PdfColors.grey400,
              ),
              pw.SizedBox(height: 20),
            ],
          );
        },
        footer: (context) {
          return pw.Column(
            children: [
              pw.Divider(
                color: PdfColors.grey300,
              ),
              pw.SizedBox(height: 6),
              pw.Row(
                mainAxisAlignment:
                pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(
                    'Generated by InvoicePilot',
                    style: pw.TextStyle(
                      fontSize: 8,
                      color: PdfColors.grey600,
                    ),
                  ),
                  pw.Text(
                    'Page ${context.pageNumber} of ${context.pagesCount}',
                    style: pw.TextStyle(
                      fontSize: 8,
                      color: PdfColors.grey600,
                    ),
                  ),
                ],
              ),
            ],
          );
        },
        build: (context) {
          return [
            pw.Row(
              crossAxisAlignment:
              pw.CrossAxisAlignment.start,
              children: [
                pw.Expanded(
                  child: _infoBox(
                    title: 'BILL TO',
                    child: pw.Text(
                      clientName,
                      style: pw.TextStyle(
                        fontSize: 15,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                  ),
                ),
                pw.SizedBox(width: 15),
                pw.Expanded(
                  child: _infoBox(
                    title: 'INVOICE DETAILS',
                    child: pw.Column(
                      crossAxisAlignment:
                      pw.CrossAxisAlignment.start,
                      children: [
                        _infoLine(
                          'Issue Date',
                          issueDate,
                        ),
                        pw.SizedBox(height: 5),
                        _infoLine(
                          'Due Date',
                          dueDate,
                        ),
                        pw.SizedBox(height: 8),
                        _statusBadge(status),
                      ],
                    ),
                  ),
                ),
              ],
            ),

            pw.SizedBox(height: 30),

            pw.Text(
              'ITEMS',
              style: pw.TextStyle(
                fontSize: 11,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.grey700,
              ),
            ),

            pw.SizedBox(height: 8),

            pw.TableHelper.fromTextArray(
              headers: const [
                'Description',
                'Amount',
              ],
              data: items.map((item) {
                final amount =
                    (item['amount'] as num?)
                        ?.toDouble() ??
                        0;

                return [
                  item['description']?.toString() ?? '',
                  '$currencySymbol${amount.toStringAsFixed(2)}',
                ];
              }).toList(),
              headerStyle: pw.TextStyle(
                fontSize: 10,
                fontWeight: pw.FontWeight.bold,
                color: PdfColors.white,
              ),
              headerDecoration: const pw.BoxDecoration(
                color: PdfColors.blue,
              ),
              cellStyle: const pw.TextStyle(
                fontSize: 11
              ),
              cellPadding: const pw.EdgeInsets.symmetric(
                horizontal: 12,
                vertical: 11,
              ),
              columnWidths: {
                0: const pw.FlexColumnWidth(3),
                1: const pw.FlexColumnWidth(1),
              },
              cellAlignments: {
                1: pw.Alignment.centerRight,
              },
              border: pw.TableBorder.all(
                color: PdfColors.grey300,
                width: 0.5,
              ),
            ),

            pw.SizedBox(height: 25),

            pw.Align(
              alignment: pw.Alignment.centerRight,
              child: pw.Container(
                width: 250,
                padding: const pw.EdgeInsets.all(18),
                decoration: pw.BoxDecoration(
                  border: pw.Border.all(
                    color: PdfColors.grey300,
                  ),
                  borderRadius: const pw.BorderRadius.all(
                    pw.Radius.circular(6),
                  ),
                ),
                child: pw.Column(
                  children: [
                    _totalRow(
                      'Subtotal',
                      subtotal,
                      currencySymbol: currencySymbol,
                    ),
                    pw.SizedBox(height: 7),
                    _totalRow(
                      'VAT',
                      vat,
                      currencySymbol: currencySymbol,
                    ),
                    pw.SizedBox(height: 10),
                    pw.Divider(
                      color: PdfColors.grey400,
                    ),
                    pw.SizedBox(height: 5),
                    _totalRow(
                      'Total',
                      total,
                      bold: true,
                      large: true,
                      currencySymbol: currencySymbol,
                    ),
                  ],
                ),
              ),
            ),

            pw.SizedBox(height: 30),

            pw.Text(
              'Thank you for your business.',
              style: pw.TextStyle(
                fontSize: 10,
                color: PdfColors.grey600,
              ),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _infoBox({
    required String title,
    required pw.Widget child,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: const pw.BorderRadius.all(
          pw.Radius.circular(6),
        ),
        border: pw.Border.all(
          color: PdfColors.grey300,
        ),
      ),
      child: pw.Column(
        crossAxisAlignment:
        pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              fontSize: 8,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey600,
            ),
          ),
          pw.SizedBox(height: 7),
          child,
        ],
      ),
    );
  }

  static pw.Widget _infoLine(
      String label,
      String value,
      ) {
    return pw.Row(
      mainAxisAlignment:
      pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(
            fontSize: 9,
            color: PdfColors.grey600,
          ),
        ),
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 9,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      ],
    );
  }

  static pw.Widget _statusBadge(String status) {
    PdfColor background;
    PdfColor textColor;

    switch (status.toLowerCase()) {
      case 'paid':
        background = PdfColors.green100;
        textColor = PdfColors.green800;
        break;

      case 'overdue':
        background = PdfColors.red100;
        textColor = PdfColors.red800;
        break;

      default:
        background = PdfColors.blue100;
        textColor = PdfColors.blue800;
    }

    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(
        horizontal: 9,
        vertical: 5,
      ),
      decoration: pw.BoxDecoration(
        color: background,
        borderRadius: const pw.BorderRadius.all(
          pw.Radius.circular(12),
        ),
      ),
      child: pw.Text(
        status.toUpperCase(),
        style: pw.TextStyle(
          fontSize: 8,
          fontWeight: pw.FontWeight.bold,
          color: textColor,
        ),
      ),
    );
  }

  static pw.Widget _totalRow(
      String label,
      double amount, {
        bool bold = false,
        bool large = false,
        required String currencySymbol,
      }) {
    final style = pw.TextStyle(
      fontSize: large
          ? 18
          : bold
          ? 13
          : 11,
      fontWeight: bold
          ? pw.FontWeight.bold
          : pw.FontWeight.normal,
    );

    return pw.Row(
      mainAxisAlignment:
      pw.MainAxisAlignment.spaceBetween,
      children: [
        pw.Text(
          label,
          style: style,
        ),
        pw.Text(
          '$currencySymbol${amount.toStringAsFixed(2)}',
          style: style,
        ),
      ],
    );
  }
}